spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  application:
    name: non-valent-gateway
  #jwt的密钥
  security:
    oauth2:
      jwt:
        signingKey: 123456